
directories:
  data: ${UDGSIZES_HOME}/data

cosmology:
  class: astropy.cosmology.FlatLambdaCDM
  name: "Standard"
  H0: 70
  Om0: 0.3
  Tcmb0: 2.725

injections:
  receff_filename: recoveff_interp.pkl
  catalogue_filename: selected.csv

defaults:
  band: "HSC-R"
  nproc: 4

dimming:
  blue:
    age: 6.7
    fsps:
      logzsol: -0.66

models:
  blue:
    pop_name: blue
    variables:
      rec_phys:
        func: rec.power
        initial: 1.5
      uae_phys:
        initial: 25
        func: uae.exponential
      redshift:
        func: redshift.mass
        min: 0.0001
        max: 0.5
        initial: 0.02
      index:
        initial: 1
      colour_rest:
        initial: 0.3
  blue_trunc:
    pop_name: blue
    variables:
      rec_phys:
        func: rec.power_trunc
        pars:
          r_trunc: 1.0
        initial: 1.5
      uae_phys:
        initial: 25
        func: uae.exponential
      redshift:
        func: redshift.mass
        min: 0.0001
        max: 0.5
        initial: 0.02
      index:
        initial: 1
      colour_rest:
        initial: 0.3

grid:
  sampling:
    n_samples: 100000
    burnin: 5000
  parameters:
    rec_phys:
      alpha:
        min: 2
        max: 5
        step: 0.05
    uae_phys:
      k:
        min: 0
        max: 2
        step: 0.05
