
directories:
  data: ${UDGSIZES_HOME}/data

cosmology:
  class: astropy.cosmology.FlatLambdaCDM
  name: "Standard"
  H0: 70
  Om0: 0.3
  Tcmb0: 2.725

injections:
  receff_filename: recoveff_interp.pkl
  catalogue_filename: selected.csv

defaults:
  band: "HSC-R"
  nproc: 4

dimming:
  blue:
    age: 6.7
    fsps:
      logzsol: -0.66

colour_model:
  selection:
    n_max: 2.5
    z_max: 0.1
  binning:
    logmstar:
      min: 8.75
      max: 11
      step: 0.25
    colour:
      min: -0.1
      max: 0.9
      step: 0.1

models:
  blue:
    pop_name: blue
    mlratio: 0.47
    type: udgsizes.model.sb_size.SbSizeModel
    variables:
      rec_phys:
        func: rec.power
        initial: 1.5
      uae_phys:
        initial: 25
        func: uae.exponential
      redshift:
        func: redshift.mass
        cosmo: True
        min: 0.001
        max: 0.5
        initial:
          min: 0.001
          max: 0.051
          step: 0.005
      index:
        initial:
          min: 0.5
          max: 1.5
          step: 0.5
      colour_rest:
        initial:
          min: 0.1
          max: 0.5
          step: 0.1

  blue_trunc:
    base: blue
    variables:
      rec_phys:
        func: rec.power_trunc
        pars:
          r_trunc: 1.0

  blue_baldry:
    base: blue
    type: udgsizes.model.smf_size.SmfSizeModel
    variables:
      logmstar:
        func: mstar.schechter_baldry
        cosmo: True
        pars:
          phi: 0.00071
          logm0: 10.72
          min: 0
        initial:
          min: 5
          max: 9
          step: 0.2

  blue_baldry_trunc:
    base: blue_baldry
    variables:
      rec_phys:
        func: rec.power_trunc
        pars:
          r_trunc: 1.0

  blue_baldry_dwarf:
    base: blue_baldry
    variables:
      logmstar:
        pars:
          logm0: 7.5

  blue_baldry_highml:
    base: blue_baldry
    mlratio: 2

  blue_baldry_shen:
    base: blue_baldry
    type: udgsizes.model.smf.SmfModel
    variables:
      rec_phys_offset:
        func: rec.gaussian_offset_shen
        initial:
          min: -0.1
          max: 0.1
          step: 0.1

  blue_baldry_shen_udg:
    base: blue_baldry_shen
    variables:
      logmstar:
        pars:
          min: 6

  blue_sedgwick_shen:
    base: blue_baldry_shen
    type: udgsizes.model.smf.SmfModel
    variables:
      logmstar:
        func: mstar.schechter_baldry
        cosmo: True
        pars:
          phi: 0.00132
          logm0: 10.54

  blue_sedgwick_shen_udg:
    base: blue_sedgwick_shen
    variables:
      logmstar:
        pars:
          min: 6


grid:
  n_samples: 100000
  burnin: 5000

  udgsizes.model.sb_size.SbSizeModel:
    parameters:
      rec_phys:
        alpha:
          min: 2
          max: 5
          step: 0.05
      uae_phys:
        k:
          min: 0
          max: 2
          step: 0.05

  udgsizes.model.smf_size.SmfSizeModel:
    parameters:
      rec_phys:
        alpha:
          min: 3
          max: 8
          step: 0.2
      logmstar:
        a:
          min: -1.5
          max: 1.5
          step: 0.2

  udgsizes.model.smf.SmfModel:
    parameters:
      rec_phys_offset:
        alpha:
          min: 0.15
          max: 0.30
          step: 0.01
      logmstar:
        a:
          min: -1.55
          max: -1.30
          step: 0.02
