
directories:
  data: ${UDGSIZES_HOME}/data
  images: ${UDGSIZES_HOME}/data/images

cosmology:
  class: astropy.cosmology.FlatLambdaCDM
  name: "Standard"
  H0: 70
  Om0: 0.3
  Tcmb0: 2.725

injections:
  receff_filename: recoveff_interp.pkl
  catalogue_filename: selected.csv

defaults:
  band: "HSC-R"
  nproc: 6

dimming:
  blue:
    age: 6.7
    fsps:
      logzsol: -0.66

ml_model:
  selection:
    n_max: 2.5
    z_max: 0.1
  binning:
    logmstar:
      min: 8.75
      max: 11
      step: 0.25
    colour:
      min: -0.1
      max: 0.9
      step: 0.1

models:
  blue:
    pop_name: blue
    mlratio: 0.47
    type: udgsizes.model.sb_size.SbSizeModel
    variables:
      rec_phys:
        func: rec.power
        initial: 1.5
      uae_phys:
        initial: 25
        func: uae.exponential
      redshift:
        func: redshift.mass
        cosmo: True
        min: 0.001
        max: 0.5
        initial:
          min: 0.001
          max: 0.151
          step: 0.001
      index:
        initial:
          min: 0.5
          max: 1.5
          step: 0.5
      colour_rest:
        initial:
          min: 0.1
          max: 0.5
          step: 0.1

  blue_baldry:
    base: blue
    type: udgsizes.model.smf_size.SmfSizeModel
    variables:
      logmstar:
        func: mstar.schechter_baldry
        cosmo: True
        pars:
          phi: 0.00071
          logm0: 10.72
          min: 0
        initial:
          min: 5
          max: 9
          step: 0.1

  blue_baldry_shen:
    base: blue_baldry
    type: udgsizes.model.smf.SmfModel
    variables:
      rec_phys_offset:
        func: rec.gaussian_offset_shen
        initial:
          min: -2.0
          max: 2.0
          step: 0.05

  blue_sedgwick_shen:
    base: blue_baldry_shen
    type: udgsizes.model.sm_size.Model
    variables:
      logmstar:
        func: mstar.schechter_baldry
        cosmo: True
        pars:
          phi: 0.00130
          logm0: 10.56
      colour_rest_offset:
        initial:
          min: -1
          max: 1
          step: 0.2

  # Fiducial model
  blue_sedgwick_shen_0.35:
    base: blue_sedgwick_shen

  # Colour distribution tests
  # NOTE: Changing the colour distribution from this config is not supported yet
  blue_sedgwick_shen_0.40:
    base: blue_sedgwick_shen

  blue_sedgwick_shen_0.42:
    base: blue_sedgwick_shen

  blue_sedgwick_shen_colour:
    base: blue_sedgwick_shen
    type: udgsizes.model.sm_size_colour.Model

  # Mass kink parameter tests
  blue_sedgwick_shen_highkink:
    base: blue_sedgwick_shen
    logmstar_kink: 10

  blue_sedgwick_shen_udg:
    base: blue_sedgwick_shen
    type: udgsizes.model.sm_size.UDGModel

grid:
  n_samples: 10000
  burnin: 1000

  udgsizes.model.sm_size.Model:
    parameters:
      rec_phys_offset:
        alpha:
          min: 0.2
          max: 0.8
          step: 0.025
      logmstar:
        a:
          min: -1.65
          max: -1.25
          step: 0.025
    priors:
      logmstar:
        a:
          func: udgsizes.model.priors.gaussian
          pars:
            mu: -1.45
            sigma: 0.05

  udgsizes.model.sm_size_colour.Model:  # Coarse sm_size model that also varies colour model
    parameters:
      rec_phys_offset:
        alpha:
          min: 0.2
          max: 0.8
          step: 0.05
      logmstar:
        a:
          min: -1.65
          max: -1.25
          step: 0.05
      colour:
        colour_min:
          min: 0.3
          max: 0.4
          step: 0.025
    priors:
      logmstar:
        a:
          func: udgsizes.model.priors.gaussian
          pars:
            mu: -1.45
            sigma: 0.05
